version: '3'

services:
    mongodb:
      image: mongo
      ports: 
      - 27017:27017
      environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin 
      - MONGO_INITDB_ROOT_PASSWORD=password
    
    mongo-express: 
      image: mongo-express
      ports:
      - 8081:8081
      environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin 
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password 
      - ME_CONFIG_MONGODB_SERVER=mongodb
      # docker network create mongodb
      # docker pull mongo
      # docker pull mongo-express
      # docker run -d -p27017:27017 --name mongodatabase -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=password --network mongodb mongo
      # docker run -d -p8081:8081 --name mongoserver -e ME_CONFIG_MONGODB_ADMINUSERNAME=admin -e ME_CONFIG_MONGODB_ADMINPASSWORD=password -e ME_CONFIG_MONGODB_SERVER=mongodatabase --network mongodb mongo-express



  